#!/usr/bin/env bash
# Copyright (c) 2026 The CryptoLari developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.
#
# Set up a CryptoLari node on a fresh Ubuntu 22.04/24.04 server (VPS).
#
#   sudo contrib/cryptolari/deploy/setup-node.sh [options]
#
# Options:
#   --testnet        run on testnet instead of mainnet
#   --explorer       also run the block explorer (port 8080)
#   --pool           also run the mining pool (stratum port 3333, stats port 8081);
#                    a pool payout address is created in the node wallet
#   --pool-fee <n>   pool fee in percent (default: 1)
#   --no-build       do not build; use the binaries already built in this checkout
#
# Run it from a checkout of the CryptoLari repository. It installs the build
# dependencies, builds the binaries, installs them to /usr/local/bin, creates a
# "cryptolari" user, writes the configuration and starts everything as systemd
# services (or as plain background processes when systemd is not available).
set -euo pipefail

NETWORK=main
EXPLORER=0
POOL=0
POOL_FEE=1
BUILD=1
while [ $# -gt 0 ]; do
    case "$1" in
        --testnet) NETWORK=test ;;
        --explorer) EXPLORER=1 ;;
        --pool) POOL=1 ;;
        --pool-fee) POOL_FEE="$2"; shift ;;
        --no-build) BUILD=0 ;;
        -h|--help) sed -n '7,24p' "$0"; exit 0 ;;
        *) echo "unknown option: $1" >&2; exit 1 ;;
    esac
    shift
done

if [ "$(id -u)" != 0 ]; then
    echo "run as root (sudo)" >&2
    exit 1
fi

SRC="$(cd "$(dirname "$0")/../../.." && pwd)"
USER_NAME=cryptolari
HOME_DIR=/var/lib/cryptolari
DATA_DIR="$HOME_DIR/.cryptolari"
CONF="$DATA_DIR/cryptolari.conf"
BIN=/usr/local/bin
SHARE=/usr/local/share/cryptolari
if [ "$NETWORK" = test ]; then
    P2P_PORT=19555; RPC_PORT=19554; CHAIN_FLAG="-testnet"; NET_DIR="$DATA_DIR/testnet"
else
    P2P_PORT=9555; RPC_PORT=9554; CHAIN_FLAG=""; NET_DIR="$DATA_DIR"
fi

log() { echo "==> $*"; }

# ------------------------------------------------------------------ build
if [ "$BUILD" = 1 ]; then
    log "installing build dependencies"
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -q
    apt-get install -y -q build-essential libtool autotools-dev automake pkg-config \
        libssl-dev libevent-dev bsdmainutils libdb++-dev python3 \
        libboost-system-dev libboost-filesystem-dev libboost-chrono-dev \
        libboost-program-options-dev libboost-test-dev libboost-thread-dev
    log "building (this takes a while)"
    cd "$SRC"
    ./autogen.sh
    ./configure --with-incompatible-bdb --without-gui --disable-tests --disable-bench
    make -j"$(nproc)"
fi

for b in cryptolarid cryptolari-cli cryptolari-tx; do
    if [ ! -x "$SRC/src/$b" ]; then
        echo "missing $SRC/src/$b: build first or drop --no-build" >&2
        exit 1
    fi
done

if [ "$NETWORK" = main ] && grep -q 'DEV_FEE_SCRIPT_MAIN = DEV_FEE_SCRIPT_PLACEHOLDER' "$SRC/src/chainparams.cpp"; then
    echo "The mainnet dev fee address is not set. Run contrib/cryptolari/set_devfee_address.py <address>, rebuild, and try again." >&2
    exit 1
fi

# ------------------------------------------------------------------ install
log "installing binaries to $BIN"
install -m 755 "$SRC/src/cryptolarid" "$SRC/src/cryptolari-cli" "$SRC/src/cryptolari-tx" "$BIN/"
mkdir -p "$SHARE"
install -m 644 "$SRC/contrib/cryptolari/explorer/explorer.py" "$SRC/contrib/cryptolari/pool/pool.py" "$SHARE/"

if ! id "$USER_NAME" >/dev/null 2>&1; then
    log "creating user $USER_NAME"
    useradd --system --home-dir "$HOME_DIR" --create-home --shell /usr/sbin/nologin "$USER_NAME"
fi
mkdir -p "$DATA_DIR"

if [ ! -f "$CONF" ]; then
    log "writing $CONF"
    RPC_PASS="$(head -c 32 /dev/urandom | base64 | tr -dc 'A-Za-z0-9')"
    {
        echo "# CryptoLari node configuration (generated by setup-node.sh)"
        [ "$NETWORK" = test ] && echo "testnet=1"
        echo "server=1"
        echo "listen=1"
        echo "rpcuser=cryptolari"
        echo "rpcpassword=$RPC_PASS"
        echo "rpcbind=127.0.0.1"
        echo "rpcallowip=127.0.0.1"
        echo "dbcache=300"
        echo "maxconnections=125"
    } > "$CONF"
fi
chown -R "$USER_NAME:$USER_NAME" "$HOME_DIR"
chmod 600 "$CONF"
RPC_USER="$(sed -n 's/^rpcuser=//p' "$CONF" | tail -1)"
RPC_PASS="$(sed -n 's/^rpcpassword=//p' "$CONF" | tail -1)"
CLI=("$BIN/cryptolari-cli" -datadir="$DATA_DIR" $CHAIN_FLAG)

# ------------------------------------------------------------------ services
HAVE_SYSTEMD=0
if [ -d /run/systemd/system ] && command -v systemctl >/dev/null; then
    HAVE_SYSTEMD=1
fi

write_unit() {  # name, description, command, after
    cat > "/etc/systemd/system/$1.service" <<EOF
[Unit]
Description=$2
After=network-online.target $4
Wants=network-online.target $4

[Service]
User=$USER_NAME
Group=$USER_NAME
WorkingDirectory=$HOME_DIR
ExecStart=$3
Restart=on-failure
RestartSec=10
TimeoutStopSec=600
PrivateTmp=true
ProtectSystem=full
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
EOF
}

start_bg() {  # name, command (fallback without systemd)
    log "systemd not available, starting $1 in the background (log: $HOME_DIR/$1.log)"
    (cd "$HOME_DIR" && runuser -u "$USER_NAME" -- setsid -f $2 >> "$HOME_DIR/$1.log" 2>&1 < /dev/null)
}

NODE_CMD="$BIN/cryptolarid -datadir=$DATA_DIR -printtoconsole"
if [ "$HAVE_SYSTEMD" = 1 ]; then
    write_unit cryptolarid "CryptoLari node" "$NODE_CMD" ""
    systemctl daemon-reload
    systemctl enable --now cryptolarid
else
    start_bg cryptolarid "$NODE_CMD"
fi

log "waiting for the node to start"
for _ in $(seq 1 60); do
    if runuser -u "$USER_NAME" -- "${CLI[@]}" getblockcount >/dev/null 2>&1; then break; fi
    sleep 2
done
runuser -u "$USER_NAME" -- "${CLI[@]}" getblockcount >/dev/null

RPC_ARGS="--chain=$NETWORK --rpcurl=http://127.0.0.1:$RPC_PORT/ --rpcuser=$RPC_USER --rpcpassword=$RPC_PASS"

if [ "$EXPLORER" = 1 ]; then
    EXPLORER_CMD="/usr/bin/python3 $SHARE/explorer.py $RPC_ARGS --bind=0.0.0.0 --port=8080 --db=$HOME_DIR/explorer-$NETWORK.sqlite"
    if [ "$HAVE_SYSTEMD" = 1 ]; then
        write_unit cryptolari-explorer "CryptoLari block explorer" "$EXPLORER_CMD" cryptolarid.service
        systemctl daemon-reload
        systemctl enable --now cryptolari-explorer
    else
        start_bg cryptolari-explorer "$EXPLORER_CMD"
    fi
fi

POOL_ADDRESS=""
if [ "$POOL" = 1 ]; then
    POOL_ADDRESS_FILE="$HOME_DIR/pool-address-$NETWORK"
    if [ ! -s "$POOL_ADDRESS_FILE" ]; then
        runuser -u "$USER_NAME" -- "${CLI[@]}" getnewaddress pool > "$POOL_ADDRESS_FILE"
    fi
    POOL_ADDRESS="$(cat "$POOL_ADDRESS_FILE")"
    POOL_CMD="/usr/bin/python3 $SHARE/pool.py $RPC_ARGS --address=$POOL_ADDRESS --fee=$POOL_FEE --port=3333 --stats-port=8081 --db=$HOME_DIR/pool-$NETWORK.sqlite"
    if [ "$HAVE_SYSTEMD" = 1 ]; then
        write_unit cryptolari-pool "CryptoLari mining pool" "$POOL_CMD" cryptolarid.service
        systemctl daemon-reload
        systemctl enable --now cryptolari-pool
    else
        start_bg cryptolari-pool "$POOL_CMD"
    fi
fi

# ------------------------------------------------------------------ firewall
if command -v ufw >/dev/null && ufw status | grep -q "Status: active"; then
    log "opening firewall ports"
    ufw allow "$P2P_PORT/tcp"
    [ "$EXPLORER" = 1 ] && ufw allow 8080/tcp
    [ "$POOL" = 1 ] && ufw allow 3333/tcp && ufw allow 8081/tcp
fi

PUBLIC_IP="$(curl -s --max-time 5 https://api.ipify.org || true)"
echo
echo "CryptoLari node is running on $NETWORK (P2P port $P2P_PORT)."
echo "  status:    sudo -u $USER_NAME ${CLI[*]} getblockchaininfo"
[ "$HAVE_SYSTEMD" = 1 ] && echo "  logs:      journalctl -u cryptolarid -f"
[ "$EXPLORER" = 1 ] && echo "  explorer:  http://${PUBLIC_IP:-<server ip>}:8080/"
if [ "$POOL" = 1 ]; then
    echo "  pool:      stratum+tcp://${PUBLIC_IP:-<server ip>}:3333  (stats: http://${PUBLIC_IP:-<server ip>}:8081/)"
    echo "  pool address (in the node wallet): $POOL_ADDRESS"
    echo "  BACK UP THE WALLET: sudo -u $USER_NAME ${CLI[*]} backupwallet $HOME_DIR/wallet-backup.dat"
fi
echo "  add this server as a seed node: contrib/cryptolari/set_seed_nodes.py ${PUBLIC_IP:-<server ip>}"
